version: '3.1'

services:

  MonSuperWP:
    image: wordpress
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    ports:
      - ${APP_DEFAULT_PORT}:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ${APP_FOLDER}:/var/www/html